routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MovieController@index');

Route::resource('/movies', 'MovieController');
Route::resource('/genres', 'GenreController');

Auth::routes();

Route::get('/home', 'HomeController@index');

app/Movie.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Movie extends Model
{
	protected $fillable = [
        'title', 'description', 'image','year','length','rating','trailer'
    ];
    public function genres()
    {
        return $this->belongsToMany('App\Genre', 'movie_genres', 'movie_id', 'genre_id')->withTimestamps();;
    }
    public function convertToHoursMins($time, $format = '%02d:%02d') {
    if ($time < 1) {
        return;
    }
    $hours = floor($time / 60);
    $minutes = ($time % 60);
    return sprintf($format, $hours, $minutes);
}
    
}

app/Http/Controllers/MovieController.php
<?php

namespace App\Http\Controllers;

use App\Movie;
use App\Genre;
use App\Movie_genre;
use Illuminate\Http\Request;

class MovieController extends Controller
{



    public function __construct()
    {
        $this->middleware('auth.admin')->except(['index', 'show']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $movies = Movie::paginate(4);
        
        return view('movie.index', compact('movies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = array();

        $genres = Genre::all();
        foreach($genres as $genre){
             $data[] =  $genre->id;
        }
        $genres = Genre::all()->sortBy('title');
        return view('movie.form', compact('genres', 'data'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|max:255',
            'description' => 'required|max:255',
            'image' => 'required|max:255',
            'length' => 'required|integer',
            'rating' => 'required|integer',
            'trailer' => 'required|max:255',
            'year' => 'required|integer'
        ]);
        
        Movie::create([
            'title' => $request->get('title'),
            'description' => $request->get('description'),
            'image' => $request->get('image'),
            'length' => $request->get('length'),
            'rating' => $request->get('rating'),
            'trailer' => $request->get('trailer'),
            'year' => $request->get('year')
        ]);
        $movie = Movie::all()->sortByDesc('id')->first();
        

        $movie->genres()->sync($request->genre);

        return redirect()->route('movies.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function show(Movie $movie)
    {
        return view('movie.show', compact('movie'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function edit(Movie $movie)
    {

        
        $genres = Genre::all()->sortBy('title');

        $data = array();
        foreach($movie->genres as $genre){
             $data[] =  $genre->id;
        }
             
        return view('movie.form', compact('data', 'movie', 'genres'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Movie $movie)
    {  
        $this->validate($request, [
            'title' => 'required|max:255',
            'description' => 'required|max:255',
            'image' => 'required|max:255',
            'length' => 'required|integer',
            'rating' => 'required|integer',
            'trailer' => 'required|max:255',
            'year' => 'required|integer'
        ]);      
        $movie->update($request->all());
        $movie->genres()->sync($request->genre);
        
        return redirect()->route('movies.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Movie  $movie
     * @return \Illuminate\Http\Response
     */
    public function destroy(Movie $movie)
    {
        
        
        $movie->delete();
        return redirect()->route('movies.index');
    }
}

resources/views/movie/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

@if(isset($movie))
    {{Form::model($movie, ['route' => ['movies.update', $movie->id], 'method' => 'put'])}}
@else
    {{Form::open(['route' => ['movies.store'], 'method' => 'post'])}}
@endif
@if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                   @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
      @endif
<div class="row"> 
    <div class="form-group col-sm-6 col-sm-offset-3">
	<label>Title:</label>
        {!!Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'title'])!!}
    </div>
</div>
<div class="row">
    <div class="form-group col-sm-6 col-sm-offset-3">
	<label>Description:</label>
        {!!Form::textarea('description', null,  ['class' => 'form-control', 'rows' => 5, 'placeholder' => 'dont write too much ..'])!!}
    </div>
</div>
<div class="row">
    <div class="form-group col-sm-6 col-sm-offset-3">
	<label>Image url:</label>
        {!!Form::text('image', null,  ['class' => 'form-control'])!!}
    </div>
</div>
<div class="row">
    <div class="form-group col-sm-6 col-sm-offset-3">
	<label>Trailer url:</label>
        {!!Form::text('trailer', null,  ['class' => 'form-control'])!!}
    </div>
</div>
<div class="row">
    <div class="form-group col-sm-2 col-sm-offset-3">
	<label>Year:</label>
        {!!Form::number('year', null,  ['class' => 'form-control'])!!}
    </div>
    <div class="form-group col-sm-2">
	<label>Length:</label>
        {!!Form::number('length', null,  ['class' => 'form-control'])!!}
    </div>
    <div class="form-group col-sm-2">
	<label>Rating:</label>
        {!!Form::number('rating', null,  ['class' => 'form-control'])!!}
    </div>
</div>
<div class="row">
    <div class="form-group col-sm-6 col-sm-offset-3">
	<label>Genres:</label><br>
        
        
		@foreach ($genres as $genre)
        
			{!! Form::label('genre', $genre->title) !!}
            {!! Form::checkbox('genre[]', $genre->id, in_array($genre->id, $data), [ 'multiple']) !!}
            <br>
		
		@endforeach
		
    </div>
</div>
<div class="row">
    <div class="form-group col-sm-6 col-sm-offset-3 btn-group">
		{!!Form::submit('Save', ['class' => 'btn btn-default'])!!}
        {!!Form::close()!!}
        
    </div>
</div>
        
</div>                
@endsection

resources/views/movie/index.blade.php
@extends('layouts.app')

@section('content')
<h1 class="text-center">
	Movies list 
	@if(Auth::user() && Auth::user()->isAdmin())
	<a href="{{route('movies.create')}}">create</a>
	@endif
</h1>
<div class="container mainContainer">

@foreach ($movies as $movie)
<div class="block">
	<div class="row">
		<div class="image">
			<a href="{{route('movies.show', $movie->id)}}">
				<img src="{{ $movie->image }}" width="100%">
			</a>			
		</div>
		<div class="content">
			<h3>{{ $movie->title }} <small> ({{ $movie->year }})</small></h3>
			<p>{{ $movie->description }}</p>
			<p>Movie length: <strong>{{$movie->convertToHoursMins($movie->length, '%0d : %02d')}}</strong> H</p>
			<p>
				Genres :
				@foreach ($movie->genres as $genre)
				<a href="{{route('genres.show', $genre->id)}}">{{ $genre->title}}</a>
				@endforeach
			</p>

		</div>
	</div>
</div>
@endforeach
{{$movies->render()}} 

</div>

@endsection

resources/views/movie/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container mainContainer showContainer">
	
	<div class="image imageShow">
		<img src="{{$movie->image}}" alt="" width="100%">
	</div>
	<div class="content">
		<h2 class="text-center">{{$movie->title}}<small> ({{ $movie->year }})</small></h2>
        <p>Description: {{$movie->description}}</p>
        <p>Movie length: <strong>{{ $movie->length }}</strong> min.</p>
        <p>
			Genres :
			@foreach ($movie->genres as $genre)
				{{ $genre->title }}
			@endforeach
		</p>
        <button type="button" class="btn btn-primary " data-toggle="modal" data-target=".bs-example-modal-lg">Watch trailer</button>

		<div id="myModal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
			<div class="modal-dialog modal-lg" role="document">
			  	<div class="modal-content">
			      <iframe  width="560" height="315" src="{{$movie->trailer}}" frameborder="0" allowfullscreen></iframe>
			    </div>
			</div>
		</div>

		@if(Auth::user() && Auth::user()->isAdmin())
        {{Form::open(['route' => ['movies.destroy', $movie->id], 'method' => 'delete'])}}
        {!!Form::submit('Delete', ['class' => 'btn btn-danger pull-right adminbutton'])!!}
        {!!Form::close()!!}
		<a href="{{route('movies.edit', $movie->id)}}" class="btn btn-default pull-right adminbutton">Edit</a>
		@endif
		
	</div>
</div>    

@endsection